### ISSUE TITLE
Long version numbers are causing problems for the packager

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/bad_judgement#1]
While looking over the packager logs I found this error from this module:

```
<em class="placeholder">EntityStorageException</em>: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column &#039;version_patch&#039; at row 1 in <em class="placeholder">NodeStorageController-&gt;save()</em> (line <em class="placeholder">301</em> of <em class="placeholder">/home/backdrop/repo/www/core/modules/node/node.entity.inc</em>).</div>
```

This is because we expect the patch version to be a tinyint (255 or less) in the database. I'm not sure if we should change the `project_release` table to allow larger numbers or if Bad Judgement should be left to intentionally break things.

As a side-effect, the project node was created on backdropcms.org (https://backdropcms.org/project/bad_judgement) but there are no releases for download.

**Comment by deekayen** [comment]
eh, I don't have to keep the joke version on the joke module. I'll get a make a more standard release version.
